# Generated by Django 3.1.5 on 2021-01-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaZakupow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.TextField()),
                ('miejscowosc', models.CharField(max_length=100)),
                ('adres', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('imie', models.CharField(max_length=15)),
                ('nazwisko', models.CharField(max_length=40)),
                ('data', models.DateField(auto_now=True)),
                ('aktywne', models.BooleanField(default=True, null=True)),
                ('realizacja', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
